version: "3.9"
services:
  mlflow-server:
    image: englabs/mlflow-server
    build:
      context: .
      dockerfile: Dockerfile-mlflow-server
    command: ["--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "s3://mlops-englab-mlflow/labstore", "--host", "0.0.0.0"]
    env_file:
      - aws.env
    ports:
      - "5000:5000"
    links:
      - torchserve
    networks:
      - englabs-net
  torchserve:
    image: englabs/torchserve
    ports:
      - "8080:8080"
      - "8081:8081" 
      - "8082:8082" 
      - "7070:7070" 
      - "7071:7071"
    networks:
      - englabs-net
networks:
  englabs-net: {}